name: Package

on: workflow_dispatch

jobs:
  package:
    name: Package extension
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: wntrblm/nox@2024.10.09
        with:
          python-versions: "3.11"

      - name: Package extension
        run: |
          nox --session build_package

      - uses: actions/upload-artifact@v4
        with:
          path: tclint-*.vsix
